### ISSUE TITLE
cdn引入状态码302

### ISSUE THREAD

**Issue by xiaoqintx** [cloydlau/imgpond#9]
![image](https://user-images.githubusercontent.com/95424027/180359303-5caf3dfe-83eb-4676-aaff-32ef98edfd29.png)
首屏加载慢

**Comment by cloydlau** [comment]
`https://unpkg.com` 替换为 `https://cdn.jsdelivr.net/npm`。

CDN 的问题也要给组件提 issue？上次也是，组件维护者没有义务也没有精力帮忙解决非组件本身的问题。
